name: simple test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:
  initial:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: action
        with:
          cache: workflow
          run: |
            mkdir -p /tmp/x
            cd /tmp/x
            touch 0 1 2 3 4 5 6 7 8 9
          path: /tmp/x
          verbose: true
      - run: ls -l /tmp/x
      - run: test "${{ steps.action.outputs.cache-hit }}" != true
  nocache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: action
        with:
          cache: no
          run: |
            mkdir -p /tmp/x
            cd /tmp/x
            touch 0 1 2 3 4 5 6 7 8 9
          path: /tmp/x
          verbose: true
      - run: ls -l /tmp/x
      - run: test "${{ steps.action.outputs.cache-hit }}" != true
  cached:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: action
        with:
          cache: workflow
          run: |
            mkdir -p /tmp/x
            cd /tmp/x
            touch 0 1 2 3 4 5 6 7 8 9
          path: /tmp/x
          verbose: true
      - run: ls -l /tmp/x
      - run: test "${{ steps.action.outputs.cache-hit }}" == true
  quiet:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: action
        with:
          cache: workflow
          run: |
            mkdir -p /tmp/x
            cd /tmp/x
            touch 0 1 2 3 4 5 6 7 8 9
          path: /tmp/x
      - run: ls -l /tmp/x
      - run: test "${{ steps.action.outputs.cache-hit }}" == true
  key:
    needs: cached
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: action
        with:
          cache: workflow
          run: |
            mkdir -p /tmp/x
            cd /tmp/x
            touch 0 1 2 3 4 5 6 7 8 9
          path: /tmp/x
          verbose: true
          key: v2
      - run: ls -l /tmp/x
      - run: test "${{ steps.action.outputs.cache-hit }}" != true
  path:
    needs: cached
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: action
        with:
          cache: workflow
          run: |
            mkdir -p /tmp/y
            cd /tmp/y
            touch 0 1 2 3 4 5 6 7 8 9
          path: /tmp/y
          verbose: true
          key: v2
      - run: ls -l /tmp/y
      - run: test "${{ steps.action.outputs.cache-hit }}" != true
